---
config:
  layout: elk
---
flowchart TD
    AWSRole[fa:fa-user-tag AWSRole]
    AZFederatedIdentityCredential[fa:fa-id-card AZFederatedIdentityCredential]
    AZUser[fa:fa-user AZUser]
    GH_AppInstallation[fa:fa-plug GH_AppInstallation]
    GH_Branch[fa:fa-code-branch GH_Branch]
    GH_Environment[fa:fa-leaf GH_Environment]
    GH_EnvironmentSecret[fa:fa-lock GH_EnvironmentSecret]
    GH_ExternalIdentity[fa:fa-arrows-left-right GH_ExternalIdentity]
    GH_Organization[fa:fa-building GH_Organization]
    GH_OrgRole[fa:fa-user-tie GH_OrgRole]
    GH_OrgSecret[fa:fa-lock GH_OrgSecret]
    GH_Repository[fa:fa-box-archive GH_Repository]
    GH_RepoRole[fa:fa-user-tie GH_RepoRole]
    GH_RepoSecret[fa:fa-lock GH_RepoSecret]
    GH_SamlIdentityProvider[fa:fa-id-badge GH_SamlIdentityProvider]
    GH_SecretScanningAlert[fa:fa-key GH_SecretScanningAlert]
    GH_Team[fa:fa-user-group GH_Team]
    GH_TeamRole[fa:fa-user-tie GH_TeamRole]
    GH_User[fa:fa-user GH_User]
    GH_Workflow[fa:fa-cogs GH_Workflow]
    GH_PersonalAccessToken[fa:fa-key GH_PersonalAccessToken]
    GH_PersonalAccessTokenRequest[fa:fa-key GH_PersonalAccessTokenRequest]
    OktaUser[fa:fa-user OktaUser]
    PingOneUser[fa:fa-user PingOneUser]

    style AWSRole fill:#FF8E40
    style AZFederatedIdentityCredential fill:#FF80D2
    style AZUser fill:#FF80D2
    style GH_AppInstallation fill:#A8D8EA
    style GH_Branch fill:#FF80D2
    style GH_Environment fill:#D5F2C2
    style GH_EnvironmentSecret fill:#6FB94A
    style GH_ExternalIdentity fill:#8A8F98
    style GH_Organization fill:#5FED83
    style GH_OrgRole fill:#BFFFD1
    style GH_OrgSecret fill:#1FB65A
    style GH_Repository fill:#9EECFF
    style GH_RepoRole fill:#DEFEFA
    style GH_RepoSecret fill:#32BEE6
    style GH_SamlIdentityProvider fill:#5A6C8F
    style GH_SecretScanningAlert fill:#3C7A6E
    style GH_Team fill:#C06EFF
    style GH_TeamRole fill:#D0B0FF
    style GH_User fill:#FF8E40
    style GH_Workflow fill:#FFE4A1
    style GH_PersonalAccessToken fill:#F5A623
    style GH_PersonalAccessTokenRequest fill:#D4A017
    style OktaUser fill:#FFE4A1
    style PingOneUser fill:#FFE4A1
    
    GH_Team -->|GH_MemberOf| GH_Team
    GH_Organization -.->|GH_Owns| GH_Repository
    GH_Organization -.->|GH_Contains| GH_OrgSecret
    GH_User -.->|GH_BypassPullRequestAllowances| GH_Branch
    GH_Team -.->|GH_BypassPullRequestAllowances| GH_Branch
    GH_User -.->|GH_RestrictionsCanPush| GH_Branch
    GH_Team -.->|GH_RestrictionsCanPush| GH_Branch
    GH_Repository -.->|GH_HasBranch| GH_Branch
    GH_Repository -.->|GH_HasWorkflow| GH_Workflow
    GH_Repository -.->|GH_HasEnvironment| GH_Environment
    GH_Branch -.->|GH_HasEnvironment| GH_Environment
    GH_Team -->|GH_HasRole| GH_OrgRole
    GH_User -->|GH_HasRole| GH_OrgRole
    GH_OrgRole -->|GH_HasBaseRole| GH_OrgRole
    GH_OrgRole -.->|GH_ManageOrganizationWebhooks| GH_Organization
    GH_OrgRole -.->|GH_OrgBypassCodeScanningDismissalRequests| GH_Organization
    GH_OrgRole -.->|GH_OrgBypassSecretScanningClosureRequests| GH_Organization
    %%GH_OrgRole -.->|GHOrgReviewAndManageSecretScanningBypassRequests| GH_Organization
    %%GH_OrgRole -.->|GHOrgReviewAndManageSecretScanningClosureRequests| GH_Organization
    %%GH_OrgRole -.->|GHReadOrganizationActionsUsageMetrics| GH_Organization
    %%GH_OrgRole -.->|GHReadOrganizationCustomOrgRole| GH_Organization
    %%GH_OrgRole -.->|GHReadOrganizationCustomRepoRole| GH_Organization
    %%GH_OrgRole -.->|GHResolveSecretScanningAlerts| GH_Organization
    %%GH_OrgRole -.->|GH_ViewSecretScanningAlerts| GH_Organization
    %%GH_OrgRole -.->|GHWriteOrganizationActionsSecrets| GH_Organization
    %%GH_OrgRole -.->|GHWriteOrganizationActionsSettings| GH_Organization
    %%GH_OrgRole -.->|GHWriteOrganizationCustomOrgRole| GH_Organization
    %%GH_OrgRole -.->|GHWriteOrganizationCustomRepoRole| GH_Organization
    %%GH_OrgRole -.->|GHWriteOrganizationNetworkConfigurations| GH_Organization
    GH_OrgRole -.->|GH_CreateRepository| GH_Organization
    GH_OrgRole -.->|GH_InviteMember| GH_Organization
    GH_OrgRole -.->|GH_AddCollaborator| GH_Organization
    GH_OrgRole -.->|GH_CreateTeam| GH_Organization
    GH_OrgRole -.->|GH_TransferRepository| GH_Organization
    GH_OrgRole -->|GH_HasBaseRole| GH_Organization
    GH_TeamRole -->|GH_MemberOf| GH_Team
    GH_TeamRole -->|GH_AddMember| GH_Team
    GH_User -->|GH_HasRole| GH_TeamRole
    GH_RepoRole -.->|GH_CanPull| GH_Repository
    GH_RepoRole -.->|GH_ReadRepoContents| GH_Repository
    GH_OrgRole -->|GH_HasBaseRole| GH_RepoRole
    GH_RepoRole -.->|GH_CanPush| GH_Repository
    GH_RepoRole -.->|GH_WriteRepoContents| GH_Repository
    %%GH_RepoRole -.->|GHWriteRepoPullRequests| GH_Repository
    GH_RepoRole -->|GH_AdminTo| GH_Repository
    %%GH_RepoRole -.->|GHManageWebhooks| GH_Repository
    %%GH_RepoRole -.->|GHManageDeployKeys| GH_Repository
    %%GH_RepoRole -.->|GHPushProtectedBranch| GH_Repository
    %%GH_RepoRole -.->|GHDeleteAlertsCodeScanning| GH_Repository
    GH_RepoRole -.->|GH_ViewSecretScanningAlerts| GH_Repository
    %%GH_RepoRole -.->|GHRunOrgMigration| GH_Repository
    GH_RepoRole -.->|GH_BypassProtections| GH_Repository
    %%GH_RepoRole -.->|GHManageSecurityProducts| GH_Repository
    %%GH_RepoRole -.->|GHManageRepoSecurityProducts| GH_Repository
    GH_RepoRole -.->|GH_EditProtections| GH_Repository
    %%GH_RepoRole -.->|GHJumpMergeQueue| GH_Repository
    %%GH_RepoRole -.->|GHCreateSoloMergeQueueEntry| GH_Repository
    %%GH_RepoRole -.->|GHEditRepoCustomPropertiesValues| GH_Repository
    GH_RepoRole -->|GH_HasBaseRole| GH_RepoRole
    GH_User -->|GH_HasRole| GH_RepoRole
    GH_Team -->|GH_HasRole| GH_RepoRole
    GH_Repository -.->|GH_HasSecret| GH_OrgSecret
    GH_Repository -.->|GH_Contains| GH_RepoSecret
    GH_Repository -.->|GH_HasSecret| GH_RepoSecret
    GH_Repository -.->|GH_HasSecretScanningAlert| GH_SecretScanningAlert
    GH_Environment -.->|GH_Contains| GH_EnvironmentSecret
    GH_Environment -.->|GH_HasSecret| GH_EnvironmentSecret

    GH_User -.->|GH_HasPersonalAccessToken| GH_PersonalAccessToken
    GH_User -.->|GH_HasPersonalAccessTokenRequest| GH_PersonalAccessTokenRequest
    GH_Organization -.->|GH_Contains| GH_PersonalAccessToken
    GH_Organization -.->|GH_Contains| GH_PersonalAccessTokenRequest
    GH_PersonalAccessToken -.->|GH_CanAccess| GH_Repository

    GH_Organization -.->|GH_HasSamlIdentityProvider| GH_SamlIdentityProvider
    GH_SamlIdentityProvider -.->|GH_HasExternalIdentity| GH_ExternalIdentity
    GH_ExternalIdentity -.->|GH_MapsToUser| GH_User
    GH_ExternalIdentity -.->|GH_MapsToUser| AZUser
    GH_ExternalIdentity -.->|GH_MapsToUser| OktaUser
    GH_ExternalIdentity -.->|GH_MapsToUser| PingOneUser
    AZUser -->|SyncedToGHUser| GH_User
    OktaUser -->|SyncedToGHUser| GH_User
    PingOneUser -->|SyncedToGHUser| GH_User
    GH_Repository -.->|GH_CanAssumeAWSRole| AWSRole
    GH_Branch -.->|GH_CanAssumeAWSRole| AWSRole
    GH_Environment -.->|GH_CanAssumeAWSRole| AWSRole
    GH_Repository -->|CanAssumeIdentity| AZFederatedIdentityCredential
    GH_Branch -->|CanAssumeIdentity| AZFederatedIdentityCredential
    GH_Environment -->|CanAssumeIdentity| AZFederatedIdentityCredential